kind: pipeline
type: kubernetes
name: development-push

trigger:
  branch:
  - development
  event: 
  - push

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker-user
    password:
      from_secret: docker-password
    registry: docker.cloud.alexfangsw.com
    repo: docker.cloud.alexfangsw.com/infra/ddns
    tags:
    - latest
    - development

# TODO: helm
